### ISSUE TITLE
afxwin.h: No such file or directory

### ISSUE THREAD

**Issue by ali-sajjad-rizavi** [Onelio/Win32GUI#1]
![image](https://user-images.githubusercontent.com/58586026/89102759-0be61b80-d3c1-11ea-9650-aca0c8f50cd1.png)

I made a file "attendance.cpp" with the sample code mentioned in README.md

```
#include "Win32/Manager.h"

int main() {
    // Create hidden window
    Window window("Hello world", 800, 600);
    // Create label
    TextView lbl(&window, "This is an autosize label"); 
    // Show Window
    window.show(); 

    // Join the WindProc & lock thread
    window.join();
}
```

**Comment by moyamejiasr** [comment]
Hi, thanks for the report.
You see, this project has been designed to compile in Visual Studio with C++ MFC and C++ ATL build tools (Usually used in the development of native applications).
This error is basically telling you that you don't have one or both of those components on your computer. 
They usually come with every Studio installation so that's why I assume in the README.md that you already have them and say "with no need of any third party frameworks".

**Comment by ali-sajjad-rizavi** [comment]
I have installed the Visual Studio 2019 including C++ desktop development tools. This means that relevant libraries and Visual C++ are installed in their default locations.
If you insist that I use Visual Studio, could you tell me what project settings do I choose?

Actually I know there is ATL build option in Visual Studio Windows Desktop Wizard C++, but I wanted to make things simple as being able to run the code from command-line.

I was actually searching for extreemly light-weight all in one GUI library for C++, because I need to make very simple application with textboxes, labels and buttons etc. So this project seems to be good if I make it work!

**Comment by moyamejiasr** [comment]
Hi again,
As long as you use Studio with MFC and Multibyte character set instead of Unicode everything should work fine. (Unicode changes the Win32Api into using wchar, which this project does not support)
Anyway, I recommend you to compile the version that I just pushed to master with some small fixes that I forgot to upload.

**Comment by ali-sajjad-rizavi** [comment]
Hi ! I got your notifications, but the problem still exists with g++ compiler. Does this mean it is not all-in-one project? And cannot be transformed into one?

**Comment by moyamejiasr** [comment]
It is an all-in-one for Visual Studio that I developed initially for personal use in different projects of mine. 
I never made it with g++ or other third parties compilers in mind so I cannot help you there. I myself am not a user of it and so I don't know how to include afxwin or if it is even possible.
Sorry.
